name: CI

on:
  pull_request:
  merge_group:

jobs:
  check:
    name: Use this action for check
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    permissions:
      contents: read # for checkout
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Check out
        uses: actions/checkout@v5
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Use this action
        uses: ./
        with:
          cache-read-only: false
          kotlin-compiler-report: false # Because there are many warnings in nowinandroid
      - name: Check out sample project
        uses: actions/checkout@v5
        with:
          repository: android/nowinandroid
          path: sample
      - name: Build sample project for check
        run: cd sample && ./gradlew :app:assembleDemoDebug
